[package]
name = "logroller"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
thiserror = "1.0"
flate2 = "1.0"
tracing-subscriber = { version = "0.3", optional = true }

[features]
default = ["tracing"]
tracing = ["dep:tracing-subscriber"]
